name: ci
on:
  push:
    branches: 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  TAG: latest
  IMAGE: pocket-idp
  PLATFORM: linux/amd64,linux/arm64
jobs:
  run:
    
    runs-on: ubuntu-latest
    steps:

      # Prepare

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Humanitec CLI
        uses: humanitec/setup-cli-action@v1
        with:
          version: "0.21.1"
      - name: Setup tflit
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.49.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Validate

      - name: Lint
        run: make lint
      - name: Simulate a humctl login
        run: |
          yq e -n '.token = "'"${HUMANITEC_TOKEN}"'"' > ~/.humctl
        env:
          HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
      - name: Test
        run: make test
        env:
          HUMANITEC_ORG: ${{ secrets.HUMANITEC_ORG }}

      # Push
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: docker buildx build --platform ${{ env.PLATFORM }} -t "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:${{ env.TAG }}" --push .
